bug-1886019: generalize s3 references to make room for gcs
mozilla-services/socorro pull request #6577
Opened 2024-04-09 19:55 UTC by relud

the GCS implementation PR was quite large, this PR is my attempt at breaking some of that work out to be reviewed separately.

2024-04-09 20:54 UTC, relud commented on webapp/crashstats/api/views.py
> +    data["raw_crash"] = has_raw_crash
i don't know how important changing these keys is, if it's important i'm happy to revert this change and worry about the s3 prefix being less than accurate later.

2024-04-16 14:55 UTC, willkg requested changes
Seems like there are a lot of changes in this PR beyond just generalizing "s3" to "storage".  I only got about 1/3 of the way through it before I realized I don't know what we're trying to do here. It'd help to have an explanation of what the goals are, what problems are being solved, etc.

2024-04-16 14:55 UTC, willkg commented on docs/tests/system_checklist.rst
> +    * Check Grafana "processor.storage.save_processed_crash"
We can't change this unless we're planning to conflate s3 and gcs metrics which I don't think we should do.

We could do something like this:

```
* In AWS:

   * Check Grafana "processor.s3.save_processed.crash"

* In GCP:

   * Check Grafana "processor.gcs.save_processed.crash"
```

2024-04-16 14:55 UTC, willkg commented on socorro/external/boto/connection_context.py
> +        )
If we pass an empty dict here is that the same as the default `Paginationconfig` for `paginate`?

2024-04-16 14:55 UTC, willkg commented on socorro/external/boto/connection_context.py
> +            if "404" in str(exc):
Is there a more specific substring we could look for? Maybe "http: 404" or something like that? If the msg ever included a crash id, those could have a 404 in them.

Having said that, this code isn't likely to be used and the S3 stuff is leaving soon anyhow, so we don't _need_ to look into this. But if we knew offhand, it'd be good to improve it.

2024-04-16 14:55 UTC, willkg commented on socorro/external/boto/crashstorage.py
> +class BotoS3CrashStorage(SimplifiedCrashDataMixin, CrashStorageBase):
This seems like a bigger architectural change with crashstorage classes, but there's no explanation of what the big picture is.

What are the main aims for this PR? What're we doing here other than generalizing "s3" to "storage"?

2024-04-16 15:42 UTC, relud commented
closing in favor of a new plan to break up the gcs changes

2024-04-16 15:42 UTC, closed without merging